// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzpbJcQ4JwTFGX_3mwRhhwbtiz4UxyIWk',
    appId: '1:293812749107:web:971500dc3a91ca65203446',
    messagingSenderId: '293812749107',
    projectId: 'fir-todo-93aba',
    authDomain: 'fir-todo-93aba.firebaseapp.com',
    storageBucket: 'fir-todo-93aba.appspot.com',
    measurementId: 'G-G25PWMQHVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzBtPehCwyoWKID9X52mik_i10wH0m1hU',
    appId: '1:293812749107:android:8135a01d2603ca7b203446',
    messagingSenderId: '293812749107',
    projectId: 'fir-todo-93aba',
    storageBucket: 'fir-todo-93aba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8-0-OSozT1S0-kPwqYNRT-KWme3UwAVw',
    appId: '1:293812749107:ios:a1cdd948b89247f8203446',
    messagingSenderId: '293812749107',
    projectId: 'fir-todo-93aba',
    storageBucket: 'fir-todo-93aba.appspot.com',
    iosBundleId: 'com.example.firebaseTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8-0-OSozT1S0-kPwqYNRT-KWme3UwAVw',
    appId: '1:293812749107:ios:103a7a7af87a0904203446',
    messagingSenderId: '293812749107',
    projectId: 'fir-todo-93aba',
    storageBucket: 'fir-todo-93aba.appspot.com',
    iosBundleId: 'com.example.firebaseTodo.RunnerTests',
  );
}
